const dragAndDropStyles = {
  dragAndDropContainer: {
    height: '238.5px',
    backgroundColor: '#F6F9FC',
    borderRadius: '10px',
    margin: '20px 0 0 7px',
    border: '1.5px #E3E9EF dashed',
  },
  dragAndDropTitle: {
    marginBottom: '8px',
    marginTop: '23px',
    fontSize: '16px',
    fontWeight: '600',
    lineHeight: '1.5',
    color: '#7D879C',
    textTransform: 'none',
    whiteSpace: 'normal',
    width: '100%',
    textAlign: 'center',
  },
  dragAndDropDivider: {
    margin: '10px 10px',
    flexShrink: '0',
    borderWidth: '0',
    borderStyle: 'solid',
    borderColor: '#7D879C',
    borderBottomWidth: 'thin',
    display: 'flex',
    whiteSpace: 'nowrap',
    textAlign: 'center',
    borderTop: '0',
    width: '5%',
  },
  dragAndDropFileContainer: {
    width: '70px',
    height: '70px',
    display: 'flex',
    overflow: 'hidden',
    bordeRadius: '8px',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(148, 201, 254, 0.1)',
  },
}

export default dragAndDropStyles
