export const ADDRESS_REGISTER_REQUEST = 'ADDRESS_REGISTER_REQUEST'
export const ADDRESS_REGISTER_SUCCESS = 'ADDRESS_REGISTER_SUCCESS'
export const ADDRESS_REGISTER_FAIL = 'ADDRESS_REGISTER_FAIL'
export const ADDRESS_REGISTER_RESET = 'ADDRESS_REGISTER_RESET'

export const ADDRESS_GET_LIST_BY_USER_REQUEST = 'ADDRESS_GET_LIST_BY_USER_REQUEST'
export const ADDRESS_GET_LIST_BY_USER_SUCCESS = 'ADDRESS_GET_LIST_BY_USER_SUCCESS'
export const ADDRESS_GET_LIST_BY_USER_FAIL = 'ADDRESS_GET_LIST_BY_USER_FAIL'
export const ADDRESS_GET_LIST_BY_USER_RESET = 'ADDRESS_GET_LIST_BY_USER_RESET'

export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL'
export const ADDRESS_UPDATE_RESET = 'ADDRESS_UPDATE_RESET'

export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST'
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS'
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL'
export const ADDRESS_DELETE_RESET = 'ADDRESS_DELETE_RESET'

export const ADDRESS_UPDATE_COORDINATES_REQUEST = 'ADDRESS_UPDATE_COORDINATES_REQUEST'
export const ADDRESS_UPDATE_COORDINATES_SUCCESS = 'ADDRESS_UPDATE_COORDINATES_SUCCESS'
export const ADDRESS_UPDATE_COORDINATES_FAIL = 'ADDRESS_UPDATE_COORDINATES_FAIL'
export const ADDRESS_UPDATE_COORDINATES_RESET = 'ADDRESS_UPDATE_COORDINATES_RESET'
