export const CARROUSEL_REGISTER_REQUEST = 'CARROUSEL_REGISTER_REQUEST'
export const CARROUSEL_REGISTER_SUCCESS = 'CARROUSEL_REGISTER_SUCCESS'
export const CARROUSEL_REGISTER_FAIL = 'CARROUSEL_REGISTER_FAIL'
export const CARROUSEL_REGISTER_RESET = 'CARROUSEL_REGISTER_RESET'


export const CARROUSEL_GET_LIST_REQUEST = 'CARROUSEL_GET_LIST_REQUEST'
export const CARROUSEL_GET_LIST_SUCCESS = 'CARROUSEL_GET_LIST_SUCCESS'
export const CARROUSEL_GET_LIST_FAIL = 'CARROUSEL_GET_LIST_FAIL'
export const CARROUSEL_GET_LIST_RESET = 'CARROUSEL_GET_LIST_RESET'
