export const DASHBOARD_GET_ALL_DATA_REQUEST = 'DASHBOARD_GET_ALL_DATA_REQUEST'
export const DASHBOARD_GET_ALL_DATA_SUCCESS = 'DASHBOARD_GET_ALL_DATA_SUCCESS'
export const DASHBOARD_GET_ALL_DATA_FAIL = 'DASHBOARD_GET_ALL_DATA_FAIL'
export const DASHBOARD_GET_ALL_DATA_RESET = 'DASHBOARD_GET_ALL_DATA_RESET'
