export const LOCATION_BY_CP_REQUEST = 'LOCATION_BY_CP_REQUEST'
export const LOCATION_BY_CP_SUCCESS = 'LOCATION_BY_CP_SUCCESS'
export const LOCATION_BY_CP_FAIL = 'LOCATION_BY_CP_FAIL'
export const LOCATION_BY_CP_RESET = 'LOCATION_BY_CP_RESET'
