export const MY_ORDER_LIST_REQUEST = 'MY_ORDER_LIST_REQUEST'
export const MY_ORDER_LIST_SUCCESS = 'MY_ORDER_LIST_SUCCESS'
export const MY_ORDER_LIST_FAIL = 'MY_ORDER_LIST_FAIL'
export const MY_ORDER_LIST_RESET = 'MY_ORDER_LIST_RESET'

export const MY_ORDER_REQUEST = 'MY_ORDER_REQUEST'
export const MY_ORDER_SUCCESS = 'MY_ORDER_SUCCESS'
export const MY_ORDER_FAIL = 'MY_ORDER_FAIL'
export const MY_ORDER_RESET = 'MY_ORDER_RESET'
