export const ORDER_GENERATE_PAYMENT_LINK_REQUEST = 'ORDER_GENERATE_PAYMENT_LINK_REQUEST'
export const ORDER_GENERATE_PAYMENT_LINK_SUCCESS = 'ORDER_GENERATE_PAYMENT_LINK_SUCCESS'
export const ORDER_GENERATE_PAYMENT_LINK_FAIL = 'ORDER_GENERATE_PAYMENT_LINK_FAIL'
export const ORDER_GENERATE_PAYMENT_LINK_RESET = 'ORDER_GENERATE_PAYMENT_LINK_RESET'

export const ORDER_GET_LIST_BY_ADMIN_REQUEST = 'ORDER_GET_LIST_BY_ADMIN_REQUEST'
export const ORDER_GET_LIST_BY_ADMIN_SUCCESS = 'ORDER_GET_LIST_BY_ADMIN_SUCCESS'
export const ORDER_GET_LIST_BY_ADMIN_FAIL = 'ORDER_GET_LIST_BY_ADMIN_FAIL'
export const ORDER_GET_LIST_BY_ADMIN_RESET = 'ORDER_GET_LIST_BY_ADMIN_RESET'

export const ORDER_GET_BY_ADMIN_REQUEST = 'ORDER_GET_BY_ADMIN_REQUEST'
export const ORDER_GET_BY_ADMIN_SUCCESS = 'ORDER_GET_BY_ADMIN_SUCCESS'
export const ORDER_GET_BY_ADMIN_FAIL = 'ORDER_GET_BY_ADMIN_FAIL'
export const ORDER_GET_BY_ADMIN_RESET = 'ORDER_GET_BY_ADMIN_RESET'

export const ORDER_GET_LIST_BY_USER_ID_REQUEST = 'ORDER_GET_LIST_BY_USER_ID_REQUEST'
export const ORDER_GET_LIST_BY_USER_ID_SUCCESS = 'ORDER_GET_LIST_BY_USER_ID_SUCCESS'
export const ORDER_GET_LIST_BY_USER_ID_FAIL = 'ORDER_GET_LIST_BY_USER_ID_FAIL'
export const ORDER_GET_LIST_BY_USER_ID_RESET = 'ORDER_GET_LIST_BY_USER_ID_RESET'

export const ORDER_UPDATE_REQUEST = 'ORDER_UPDATE_REQUEST'
export const ORDER_UPDATE_SUCCESS = 'ORDER_UPDATE_SUCCESS'
export const ORDER_UPDATE_FAIL = 'ORDER_UPDATE_FAIL'
export const ORDER_UPDATE_RESET = 'ORDER_UPDATE_RESET'

export const ORDER_GENERATE_REQUEST = 'ORDER_GENERATE_REQUEST'
export const ORDER_GENERATE_SUCCESS = 'ORDER_GENERATE_SUCCESS'
export const ORDER_GENERATE_FAIL = 'ORDER_GENERATE_FAIL'
export const ORDER_GENERATE_RESET = 'ORDER_GENERATE_RESET'
