export const PRODUCT_REGISTER_REQUEST = 'PRODUCT_REGISTER_REQUEST'
export const PRODUCT_REGISTER_SUCCESS = 'PRODUCT_REGISTER_SUCCESS'
export const PRODUCT_REGISTER_FAIL = 'PRODUCT_REGISTER_FAIL'
export const PRODUCT_REGISTER_RESET = 'PRODUCT_REGISTER_RESET'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
export const PRODUCT_DELETE_RESET = 'PRODUCT_DELETE_RESET'

export const PRODUCT_UPDATE_REQUEST = 'PRODUCT_UPDATE_REQUEST'
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS'
export const PRODUCT_UPDATE_FAIL = 'PRODUCT_UPDATE_FAIL'
export const PRODUCT_UPDATE_RESET = 'PRODUCT_UPDATE_RESET'

export const PRODUCT_GET_ALL_REQUEST = 'PRODUCT_GET_ALL_REQUEST'
export const PRODUCT_GET_ALL_SUCCESS = 'PRODUCT_GET_ALL_SUCCESS'
export const PRODUCT_GET_ALL_FAIL = 'PRODUCT_GET_ALL_FAIL'
export const PRODUCT_GET_ALL_RESET = 'PRODUCT_GET_ALL_RESET'
