export const STOCK_GET_ALL_REQUEST = 'STOCK_GET_ALL_REQUEST'
export const STOCK_GET_ALL_SUCCESS = 'STOCK_GET_ALL_SUCCESS'
export const STOCK_GET_ALL_FAIL = 'STOCK_GET_ALL_FAIL'
export const STOCK_GET_ALL_RESET = 'STOCK_GET_ALL_RESET'
