export const SUPPLIER_REGISTER_REQUEST = 'SUPPLIER_REGISTER_REQUEST'
export const SUPPLIER_REGISTER_SUCCESS = 'SUPPLIER_REGISTER_SUCCESS'
export const SUPPLIER_REGISTER_FAIL = 'SUPPLIER_REGISTER_FAIL'
export const SUPPLIER_REGISTER_RESET = 'SUPPLIER_REGISTER_RESET'

export const SUPPLIER_UPDATE_REQUEST = 'SUPPLIER_UPDATE_REQUEST'
export const SUPPLIER_UPDATE_SUCCESS = 'SUPPLIER_UPDATE_SUCCESS'
export const SUPPLIER_UPDATE_FAIL = 'SUPPLIER_UPDATE_FAIL'
export const SUPPLIER_UPDATE_RESET = 'SUPPLIER_UPDATE_RESET'

export const SUPPLIER_GET_LIST_REQUEST = 'SUPPLIER_GET_LIST_REQUEST'
export const SUPPLIER_GET_LIST_SUCCESS = 'SUPPLIER_GET_LIST_SUCCESS'
export const SUPPLIER_GET_LIST_FAIL = 'SUPPLIER_GET_LIST_FAIL'
export const SUPPLIER_GET_LIST_RESET = 'SUPPLIER_GET_LIST_RESET'

export const SUPPLIER_GET_LIST_BY_CATEGORY_ID_REQUEST = 'SUPPLIER_GET_LIST_BY_CATEGORY_ID_REQUEST'
export const SUPPLIER_GET_LIST_BY_CATEGORY_ID_SUCCESS = 'SUPPLIER_GET_LIST_BY_CATEGORY_ID_SUCCESS'
export const SUPPLIER_GET_LIST_BY_CATEGORY_ID_FAIL = 'SUPPLIER_GET_LIST_BY_CATEGORY_ID_FAIL'
export const SUPPLIER_GET_LIST_BY_CATEGORY_ID_RESET = 'SUPPLIER_GET_LIST_BY_CATEGORY_ID_RESET'

export const SUPPLIER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST'
export const SUPPLIER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS'
export const SUPPLIER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL'
export const SUPPLIER_DELETE_RESET = 'SUPPLIER_DELETE_RESET'

export const SUPPLIER_UPLOAD_PRODUCTS_REQUEST = 'SUPPLIER_UPLOAD_PRODUCTS_REQUEST'
export const SUPPLIER_UPLOAD_PRODUCTS_SUCCESS = 'SUPPLIER_UPLOAD_PRODUCTS_SUCCESS'
export const SUPPLIER_UPLOAD_PRODUCTS_FAIL = 'SUPPLIER_UPLOAD_PRODUCTS_FAIL'
export const SUPPLIER_UPLOAD_PRODUCTS_RESET = 'SUPPLIER_UPLOAD_PRODUCTS_RESET'

export const SUPPLIER_GET_PRODUCTS_REQUEST = 'SUPPLIER_GET_PRODUCTS_REQUEST'
export const SUPPLIER_GET_PRODUCTS_SUCCESS = 'SUPPLIER_GET_PRODUCTS_SUCCESS'
export const SUPPLIER_GET_PRODUCTS_FAIL = 'SUPPLIER_GET_PRODUCTS_FAIL'
export const SUPPLIER_GET_PRODUCTS_RESET = 'SUPPLIER_GET_PRODUCTS_RESET'

export const SUPPLIER_GET_PRODUCTS_PAGE_REQUEST = 'SUPPLIER_GET_PRODUCTS_PAGE_REQUEST'
export const SUPPLIER_GET_PRODUCTS_PAGE_SUCCESS = 'SUPPLIER_GET_PRODUCTS_PAGE_SUCCESS'
export const SUPPLIER_GET_PRODUCTS_PAGE_FAIL = 'SUPPLIER_GET_PRODUCTS_PAGE_FAIL'
export const SUPPLIER_GET_PRODUCTS_PAGE_RESET = 'SUPPLIER_GET_PRODUCTS_PAGE_RESET'
